language: node_js

matrix:
  include:
    - node_js: '4.8.7'
    - node_js: '6.10.1'

sudo: false

install:
  - travis_retry npm install

script:
  - npm run eslint
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
