service: babel-dynamically-entries-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  first:
    handler: first.hello
    events:
      - http:
          method: get
          path: first
          integration: lambda
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
          integration: lambda
